pipeline {
    agent {
        docker {
            image 'node:latest'
            args '-p 3000:3000'
        }
    }
    environment { 
        CI = 'true'
        FIREBASE_DEPLOY_TOKEN = credentials('FIREBASE_TOKEN') 
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Staging') { 
            steps {
                sh './jenkins/scripts/staging.sh' 
                input message: 'Finished using the Staging version of the Web App? (Click "Proceed" to continue)' 
            }
        }
        stage('Production') { 
            steps {
                sh './jenkins/scripts/production.sh' 
            }
        }
    }
}